In [1]:
import numpy as np

In [3]:
revenue = np.array([
    [1000, 1500, 1200],
    [1700, 1100, 1400],
    [1300, 1600, 1250]
])
expenses = np.array([
    [400, 700, 500],
    [800, 600, 750],
    [550, 900, 650]
])

In [5]:
profit = revenue-expenses
profit

array([[600, 800, 700],
       [900, 500, 650],
       [750, 700, 600]])

In [6]:
price_per_unit = np.array([1000,800,1200])
units = np.array([[30,40,50],[5,20,12],[2,34,5]])

In [ ]:
# price_per_unit*units

array([[30000, 32000, 60000],
       [ 5000, 16000, 14400],
       [ 2000, 27200,  6000]])

In [10]:
np.dot(price_per_unit, units)

array([36400, 96800, 65600])

# HOME WORK

In [14]:
dollars = np.array([[200,220,250],
                  [68,79,105],
                  [110,140,180],
                  [80,85,90]])

In [15]:
# Assuming 'dollars' is in USD, and we want to convert to INR (Indian Rupees)
# Let's use an example conversion rate, e.g., 1 USD = 83 INR

conversion_rate = 83  # 1 USD = 83 INR
inr = dollars * conversion_rate
inr


array([[16600, 18260, 20750],
       [ 5644,  6557,  8715],
       [ 9130, 11620, 14940],
       [ 6640,  7055,  7470]])

In [ ]:
a